import { collection, addDoc, getDocs, getDocsFromCache, query, where, doc, getDoc, getDocFromCache, updateDoc, deleteDoc } from 'firebase/firestore';
import { db } from '../config/firebaseConfig';
import { Group, Trip, Event, Expense, Document, PackingItem } from '../types';

/**
 * Creates a new Group document in Firestore.
 * The document ID is auto-generated by Firestore and returned as part of the Group object.
 */
export const createGroup = async (
  name: string,
  createdBy: string
): Promise<Group> => {
  const groupsCollection = collection(db, 'groups');
  const docRef = await addDoc(groupsCollection, {
    name,
    createdBy,
  });
  
  return {
    id: docRef.id,
    name,
    createdBy,
  };
};

/**
 * Creates a new Trip document in Firestore, linking it to a Group via groupId.
 * The document ID is auto-generated by Firestore and returned as part of the Trip object.
 */
export const createTrip = async (
  groupId: string,
  name: string,
  startDate: string,
  endDate: string,
  status: string,
  baseCurrency?: string,
  exchangeRateToILS?: number,
  createdBy?: string
): Promise<Trip> => {
  const tripsCollection = collection(db, 'trips');
  const data: any = {
    groupId,
    name,
    startDate,
    endDate,
    status,
  };
  if (baseCurrency !== undefined) data.baseCurrency = baseCurrency;
  if (exchangeRateToILS !== undefined) data.exchangeRateToILS = exchangeRateToILS;
  if (createdBy !== undefined) data.createdBy = createdBy;

  const docRef = await addDoc(tripsCollection, data);

  return {
    id: docRef.id,
    groupId,
    name,
    startDate,
    endDate,
    status,
    baseCurrency,
    exchangeRateToILS,
  };
};

/**
 * Saves a new Trip for a user.
 * If the user does not have an existing Group (where createdBy === userId),
 * it automatically creates a default Group for them first, then creates the Trip associated with it.
 */
export const saveTripForUser = async (
  userId: string,
  name: string,
  startDate: string,
  endDate: string
): Promise<Trip> => {
  const groupsCollection = collection(db, 'groups');
  let querySnapshot;
  try {
    const q = query(groupsCollection, where('createdBy', '==', userId));
    querySnapshot = await getDocs(q);
  } catch (err) {
    console.warn('[dbService] Group query failed, checking offline cache:', err);
    try {
      const q = query(groupsCollection, where('createdBy', '==', userId));
      querySnapshot = await getDocsFromCache(q);
    } catch (cErr) {
      console.error('[dbService] Cache query for groups failed:', cErr);
    }
  }

  let groupId = '';

  if (querySnapshot && !querySnapshot.empty) {
    const firstGroupDoc = querySnapshot.docs[0];
    groupId = firstGroupDoc.id;
  } else {
    const defaultGroupName = 'My Travel Group';
    const newGroup = await createGroup(defaultGroupName, userId);
    groupId = newGroup.id;
  }

  return createTrip(groupId, name, startDate, endDate, 'planned', undefined, undefined, userId);
};

/**
 * Fetches all trips associated with groups created by the specified user.
 */
export const getTripsForUser = async (userId: string): Promise<Trip[]> => {
  const groupsCollection = collection(db, 'groups');
  const qGroup = query(groupsCollection, where('createdBy', '==', userId));
  const groupSnapshot = await getDocs(qGroup);

  if (groupSnapshot.empty) {
    return [];
  }

  const groupIds = groupSnapshot.docs.map((doc) => doc.id);

  // Retrieve trips whose groupId belongs to the user's groups
  const tripsCollection = collection(db, 'trips');
  const qTrips = query(tripsCollection, where('groupId', 'in', groupIds));
  const tripsSnapshot = await getDocs(qTrips);

  return tripsSnapshot.docs.map((doc) => {
    const data = doc.data();
    return {
      id: doc.id,
      groupId: data.groupId,
      name: data.name,
      startDate: data.startDate,
      endDate: data.endDate,
      status: data.status,
      baseCurrency: data.baseCurrency,
      exchangeRateToILS: data.exchangeRateToILS,
    } as Trip;
  });
};

/**
 * Saves a new Event to the 'events' collection in Firestore.
 */
export const createEvent = async (
  tripId: string,
  title: string,
  type: 'flight' | 'hotel' | 'waypoint',
  startTime: string,
  endTime: string,
  latitude?: number,
  longitude?: number,
  bookingReference?: string,
  description?: string,
  flightNumber?: string,
  airline?: string,
  departureTime?: string,
  arrivalTime?: string,
  originAirport?: string,
  destinationAirport?: string,
  hotelUrl?: string,
  checkInTime?: string,
  checkOutTime?: string,
  roomType?: string,
  breakfastIncluded?: boolean,
  distance?: number,
  estimatedTravelTime?: string,
  qrCodeUrl?: string,
  transportMode?: string,
  cost?: number,
  originLatitude?: number,
  originLongitude?: number,
  address?: string,
  routePolyline?: string
): Promise<Event> => {
  const eventsCollection = collection(db, 'events');
  const data: any = {
    tripId,
    title,
    type,
    startTime,
    endTime,
  };
  if (latitude !== undefined) data.latitude = latitude;
  if (longitude !== undefined) data.longitude = longitude;
  if (bookingReference !== undefined) data.bookingReference = bookingReference;
  if (description !== undefined) data.description = description;
  if (flightNumber !== undefined) data.flightNumber = flightNumber;
  if (airline !== undefined) data.airline = airline;
  if (departureTime !== undefined) data.departureTime = departureTime;
  if (arrivalTime !== undefined) data.arrivalTime = arrivalTime;
  if (originAirport !== undefined) data.originAirport = originAirport;
  if (destinationAirport !== undefined) data.destinationAirport = destinationAirport;
  if (hotelUrl !== undefined) data.hotelUrl = hotelUrl;
  if (checkInTime !== undefined) data.checkInTime = checkInTime;
  if (checkOutTime !== undefined) data.checkOutTime = checkOutTime;
  if (roomType !== undefined) data.roomType = roomType;
  if (breakfastIncluded !== undefined) data.breakfastIncluded = breakfastIncluded;
  if (distance !== undefined) data.distance = distance;
  if (estimatedTravelTime !== undefined) data.estimatedTravelTime = estimatedTravelTime;
  if (qrCodeUrl !== undefined) data.qrCodeUrl = qrCodeUrl;
  if (transportMode !== undefined) data.transportMode = transportMode;
  if (cost !== undefined) data.cost = cost;
  if (originLatitude !== undefined) data.originLatitude = originLatitude;
  if (originLongitude !== undefined) data.originLongitude = originLongitude;
  if (address !== undefined) data.address = address;
  if (routePolyline !== undefined) data.routePolyline = routePolyline;

  const docRef = await addDoc(eventsCollection, data);

  return {
    id: docRef.id,
    tripId,
    title,
    type,
    startTime,
    endTime,
    latitude,
    longitude,
    bookingReference,
    description,
    flightNumber,
    airline,
    departureTime,
    arrivalTime,
    originAirport,
    destinationAirport,
    hotelUrl,
    checkInTime,
    checkOutTime,
    roomType,
    breakfastIncluded,
    distance,
    estimatedTravelTime,
    qrCodeUrl,
    transportMode,
    cost,
    originLatitude,
    originLongitude,
    address,
    routePolyline,
  };
};

/**
 * Fetches all events associated with a specific tripId from Firestore.
 */
export const getEventsForTrip = async (tripId: string): Promise<Event[]> => {
  const eventsCollection = collection(db, 'events');
  const q = query(eventsCollection, where('tripId', '==', tripId));
  
  let querySnapshot;
  try {
    querySnapshot = await getDocs(q);
  } catch (err) {
    console.warn('[dbService] Network unavailable for getEventsForTrip, reading from offline cache:', err);
    try {
      querySnapshot = await getDocsFromCache(q);
    } catch (cacheErr) {
      console.error('[dbService] Cache query failed for getEventsForTrip:', cacheErr);
      return [];
    }
  }

  return querySnapshot.docs.map((doc) => {
    const data = doc.data();
    return {
      id: doc.id,
      tripId: data.tripId,
      title: data.title,
      type: data.type,
      startTime: data.startTime,
      endTime: data.endTime,
      latitude: data.latitude,
      longitude: data.longitude,
      originLatitude: data.originLatitude,
      originLongitude: data.originLongitude,
      address: data.address,
      bookingReference: data.bookingReference,
      description: data.description,
      flightNumber: data.flightNumber,
      airline: data.airline,
      departureTime: data.departureTime,
      arrivalTime: data.arrivalTime,
      originAirport: data.originAirport,
      destinationAirport: data.destinationAirport,
      hotelUrl: data.hotelUrl,
      checkInTime: data.checkInTime,
      checkOutTime: data.checkOutTime,
      roomType: data.roomType,
      breakfastIncluded: data.breakfastIncluded,
      distance: data.distance,
      estimatedTravelTime: data.estimatedTravelTime,
      qrCodeUrl: data.qrCodeUrl,
      routePolyline: data.routePolyline,
      transportMode: data.transportMode,
      cost: data.cost,
    } as Event;
  });
};

/**
 * Saves a new Expense to the 'expenses' collection in Firestore.
 * Requires querying the associated trip document to find the correct groupId first.
 */
export const createExpense = async (
  tripId: string,
  amount: number,
  currency: string,
  category: string,
  description: string
): Promise<Expense> => {
  const tripDocRef = doc(db, 'trips', tripId);
  const tripSnapshot = await getDoc(tripDocRef);
  if (!tripSnapshot.exists()) {
    throw new Error('Associated trip does not exist.');
  }
  const tripData = tripSnapshot.data();
  const groupId = tripData.groupId;

  const expensesCollection = collection(db, 'expenses');
  const docRef = await addDoc(expensesCollection, {
    tripId,
    groupId,
    amount,
    currency,
    category,
    description,
    date: new Date().toISOString().split('T')[0],
  });

  return {
    id: docRef.id,
    tripId,
    groupId,
    amount,
    currency,
    category,
    date: new Date().toISOString().split('T')[0],
    description,
  };
};

/**
 * Fetches all expenses associated with a specific tripId from Firestore.
 */
export const getExpensesForTrip = async (tripId: string): Promise<Expense[]> => {
  const expensesCollection = collection(db, 'expenses');
  const q = query(expensesCollection, where('tripId', '==', tripId));
  const querySnapshot = await getDocs(q);

  return querySnapshot.docs.map((doc) => {
    const data = doc.data();
    return {
      id: doc.id,
      tripId: data.tripId,
      groupId: data.groupId,
      amount: data.amount,
      currency: data.currency,
      category: data.category,
      date: data.date,
      description: data.description,
    } as Expense;
  });
};

/**
 * Saves document metadata to the 'documents' collection in Firestore.
 */
export const saveDocument = async (
  tripId: string,
  name: string,
  downloadUrl: string,
  eventId?: string
): Promise<Document> => {
  const documentsCollection = collection(db, 'documents');
  const data: any = {
    tripId,
    name,
    downloadUrl,
  };
  if (eventId) {
    data.eventId = eventId;
  }

  const docRef = await addDoc(documentsCollection, data);

  return {
    id: docRef.id,
    tripId,
    name,
    downloadUrl,
    ...(eventId ? { eventId } : {}),
  };
};

/**
 * Fetches all document metadata documents associated with a specific tripId from Firestore.
 */
export const getDocumentsForTrip = async (tripId: string): Promise<Document[]> => {
  const documentsCollection = collection(db, 'documents');
  const q = query(documentsCollection, where('tripId', '==', tripId));
  const querySnapshot = await getDocs(q);

  return querySnapshot.docs.map((doc) => {
    const data = doc.data();
    return {
      id: doc.id,
      tripId: data.tripId,
      eventId: data.eventId,
      name: data.name,
      downloadUrl: data.downloadUrl,
    } as Document;
  });
};

/**
 * Creates a new PackingItem document in Firestore under 'packingItems'.
 */
export const createPackingItem = async (
  tripId: string,
  itemName: string,
  category: string
): Promise<PackingItem> => {
  const packingItemsCollection = collection(db, 'packingItems');
  const data = {
    tripId,
    itemName,
    category,
    isPacked: false,
  };
  const docRef = await addDoc(packingItemsCollection, data);
  return {
    id: docRef.id,
    ...data,
  };
};

/**
 * Fetches all packing items associated with a specific tripId from Firestore.
 */
export const getPackingItemsForTrip = async (tripId: string): Promise<PackingItem[]> => {
  const packingItemsCollection = collection(db, 'packingItems');
  const q = query(packingItemsCollection, where('tripId', '==', tripId));
  const querySnapshot = await getDocs(q);

  return querySnapshot.docs.map((doc) => {
    const data = doc.data();
    return {
      id: doc.id,
      tripId: data.tripId,
      itemName: data.itemName,
      category: data.category,
      isPacked: !!data.isPacked,
    } as PackingItem;
  });
};

/**
 * Updates the packed status flag of a specific packing item in Firestore.
 */
export const updatePackingItemPacked = async (
  itemId: string,
  isPacked: boolean
): Promise<void> => {
  const itemDocRef = doc(db, 'packingItems', itemId);
  await updateDoc(itemDocRef, { isPacked });
};

/**
 * Deletes a specific packing item from Firestore.
 */
export const deletePackingItem = async (itemId: string): Promise<void> => {
  const itemDocRef = doc(db, 'packingItems', itemId);
  await deleteDoc(itemDocRef);
};

/**
 * Fetches a single Trip document by its ID.
 */
export const getTrip = async (tripId: string): Promise<Trip | null> => {
  const tripDocRef = doc(db, 'trips', tripId);
  let tripSnapshot;
  try {
    tripSnapshot = await getDoc(tripDocRef);
  } catch (err) {
    console.warn('[dbService] Network unavailable for getTrip, reading from offline cache:', err);
    try {
      tripSnapshot = await getDocFromCache(tripDocRef);
    } catch (cacheErr) {
      console.error('[dbService] Cache query failed for getTrip:', cacheErr);
      return null;
    }
  }
  if (!tripSnapshot || !tripSnapshot.exists()) {
    return null;
  }
  const data = tripSnapshot.data();
  return {
    id: tripSnapshot.id,
    groupId: data.groupId,
    name: data.name,
    startDate: data.startDate,
    endDate: data.endDate,
    status: data.status,
    baseCurrency: data.baseCurrency,
    exchangeRateToILS: data.exchangeRateToILS,
  } as Trip;
};

/**
 * Updates the currency settings for a specific trip in Firestore.
 */
export const updateTripSettings = async (
  tripId: string,
  baseCurrency: string,
  exchangeRateToILS: number
): Promise<void> => {
  const tripDocRef = doc(db, 'trips', tripId);
  await updateDoc(tripDocRef, {
    baseCurrency,
    exchangeRateToILS,
  });
};

/**
 * Updates a trip's name, dates, and optional status in Firestore.
 */
export const updateTripDetails = async (
  tripId: string,
  name: string,
  startDate: string,
  endDate: string,
  status?: string
): Promise<void> => {
  const tripDocRef = doc(db, 'trips', tripId);
  const data: any = { name, startDate, endDate };
  if (status) data.status = status;
  await updateDoc(tripDocRef, data);
};

/**
 * Updates the status (e.g. 'planned', 'archived', 'completed') of a trip in Firestore.
 */
export const updateTripStatus = async (
  tripId: string,
  status: 'planned' | 'archived' | 'completed'
): Promise<void> => {
  const tripDocRef = doc(db, 'trips', tripId);
  await updateDoc(tripDocRef, { status });
};

/**
 * Deletes a trip document from Firestore along with its associated events, expenses, and documents.
 */
export const deleteTrip = async (tripId: string): Promise<void> => {
  // Delete associated events
  try {
    const eventsColl = collection(db, 'events');
    const qEvents = query(eventsColl, where('tripId', '==', tripId));
    const eventsSnap = await getDocs(qEvents);
    await Promise.all(eventsSnap.docs.map((d) => deleteDoc(d.ref)));
  } catch (err) {
    console.error('Error deleting associated events:', err);
  }

  // Delete associated expenses
  try {
    const expColl = collection(db, 'expenses');
    const qExp = query(expColl, where('tripId', '==', tripId));
    const expSnap = await getDocs(qExp);
    await Promise.all(expSnap.docs.map((d) => deleteDoc(d.ref)));
  } catch (err) {
    console.error('Error deleting associated expenses:', err);
  }

  // Delete associated documents
  try {
    const docsColl = collection(db, 'documents');
    const qDocs = query(docsColl, where('tripId', '==', tripId));
    const docsSnap = await getDocs(qDocs);
    await Promise.all(docsSnap.docs.map((d) => deleteDoc(d.ref)));
  } catch (err) {
    console.error('Error deleting associated documents:', err);
  }

  // Delete the trip document itself
  const tripDocRef = doc(db, 'trips', tripId);
  await deleteDoc(tripDocRef);
};

/**
 * Deletes an event document from Firestore by eventId.
 */
export const deleteEvent = async (eventId: string): Promise<void> => {
  const eventDocRef = doc(db, 'events', eventId);
  await deleteDoc(eventDocRef);
};

/**
 * Updates an existing event document in Firestore.
 */
export const updateEvent = async (eventId: string, eventData: Partial<Event>): Promise<void> => {
  const eventDocRef = doc(db, 'events', eventId);
  const cleanData: any = {};
  Object.keys(eventData).forEach((key) => {
    const val = (eventData as any)[key];
    if (val !== undefined) {
      cleanData[key] = val;
    }
  });
  await updateDoc(eventDocRef, cleanData);
};
