import { collection, addDoc, getDocs, query, where, doc, getDoc } from 'firebase/firestore';
import { db } from '../config/firebaseConfig';
import { Group, Trip, Event, Expense, Document } from '../types';

/**
 * Creates a new Group document in Firestore.
 * The document ID is auto-generated by Firestore and returned as part of the Group object.
 */
export const createGroup = async (
  name: string,
  createdBy: string
): Promise<Group> => {
  const groupsCollection = collection(db, 'groups');
  const docRef = await addDoc(groupsCollection, {
    name,
    createdBy,
  });
  
  return {
    id: docRef.id,
    name,
    createdBy,
  };
};

/**
 * Creates a new Trip document in Firestore, linking it to a Group via groupId.
 * The document ID is auto-generated by Firestore and returned as part of the Trip object.
 */
export const createTrip = async (
  groupId: string,
  name: string,
  startDate: string,
  endDate: string,
  status: string
): Promise<Trip> => {
  const tripsCollection = collection(db, 'trips');
  const docRef = await addDoc(tripsCollection, {
    groupId,
    name,
    startDate,
    endDate,
    status,
  });

  return {
    id: docRef.id,
    groupId,
    name,
    startDate,
    endDate,
    status,
  };
};

/**
 * Saves a new Trip for a user.
 * If the user does not have an existing Group (where createdBy === userId),
 * it automatically creates a default Group for them first, then creates the Trip associated with it.
 */
export const saveTripForUser = async (
  userId: string,
  name: string,
  startDate: string,
  endDate: string
): Promise<Trip> => {
  const groupsCollection = collection(db, 'groups');
  const q = query(groupsCollection, where('createdBy', '==', userId));
  const querySnapshot = await getDocs(q);

  let groupId = '';

  if (!querySnapshot.empty) {
    // User already has a group, use the first one
    const firstGroupDoc = querySnapshot.docs[0];
    groupId = firstGroupDoc.id;
  } else {
    // User does not belong to any group, auto-create a default group
    const defaultGroupName = 'My Travel Group';
    const newGroup = await createGroup(defaultGroupName, userId);
    groupId = newGroup.id;
  }

  // Save the trip under the selected group
  return createTrip(groupId, name, startDate, endDate, 'planned');
};

/**
 * Fetches all trips associated with groups created by the specified user.
 */
export const getTripsForUser = async (userId: string): Promise<Trip[]> => {
  const groupsCollection = collection(db, 'groups');
  const qGroup = query(groupsCollection, where('createdBy', '==', userId));
  const groupSnapshot = await getDocs(qGroup);

  if (groupSnapshot.empty) {
    return [];
  }

  const groupIds = groupSnapshot.docs.map((doc) => doc.id);

  // Retrieve trips whose groupId belongs to the user's groups
  const tripsCollection = collection(db, 'trips');
  const qTrips = query(tripsCollection, where('groupId', 'in', groupIds));
  const tripsSnapshot = await getDocs(qTrips);

  return tripsSnapshot.docs.map((doc) => {
    const data = doc.data();
    return {
      id: doc.id,
      groupId: data.groupId,
      name: data.name,
      startDate: data.startDate,
      endDate: data.endDate,
      status: data.status,
    } as Trip;
  });
};

/**
 * Saves a new Event to the 'events' collection in Firestore.
 */
export const createEvent = async (
  tripId: string,
  title: string,
  type: string,
  startTime: string,
  endTime: string,
  latitude?: number,
  longitude?: number,
  bookingReference?: string,
  description?: string
): Promise<Event> => {
  const eventsCollection = collection(db, 'events');
  const data: any = {
    tripId,
    title,
    type,
    startTime,
    endTime,
  };
  if (latitude !== undefined) data.latitude = latitude;
  if (longitude !== undefined) data.longitude = longitude;
  if (bookingReference !== undefined) data.bookingReference = bookingReference;
  if (description !== undefined) data.description = description;

  const docRef = await addDoc(eventsCollection, data);

  return {
    id: docRef.id,
    tripId,
    title,
    type,
    startTime,
    endTime,
    latitude,
    longitude,
    bookingReference,
    description,
  };
};

/**
 * Fetches all events associated with a specific tripId from Firestore.
 */
export const getEventsForTrip = async (tripId: string): Promise<Event[]> => {
  const eventsCollection = collection(db, 'events');
  const q = query(eventsCollection, where('tripId', '==', tripId));
  const querySnapshot = await getDocs(q);

  return querySnapshot.docs.map((doc) => {
    const data = doc.data();
    return {
      id: doc.id,
      tripId: data.tripId,
      title: data.title,
      type: data.type,
      startTime: data.startTime,
      endTime: data.endTime,
      latitude: data.latitude,
      longitude: data.longitude,
      bookingReference: data.bookingReference,
      description: data.description,
    } as Event;
  });
};

/**
 * Saves a new Expense to the 'expenses' collection in Firestore.
 * Requires querying the associated trip document to find the correct groupId first.
 */
export const createExpense = async (
  tripId: string,
  amount: number,
  currency: string,
  category: string,
  description: string
): Promise<Expense> => {
  const tripDocRef = doc(db, 'trips', tripId);
  const tripSnapshot = await getDoc(tripDocRef);
  if (!tripSnapshot.exists()) {
    throw new Error('Associated trip does not exist.');
  }
  const tripData = tripSnapshot.data();
  const groupId = tripData.groupId;

  const expensesCollection = collection(db, 'expenses');
  const docRef = await addDoc(expensesCollection, {
    tripId,
    groupId,
    amount,
    currency,
    category,
    description,
    date: new Date().toISOString().split('T')[0],
  });

  return {
    id: docRef.id,
    tripId,
    groupId,
    amount,
    currency,
    category,
    date: new Date().toISOString().split('T')[0],
    description,
  };
};

/**
 * Fetches all expenses associated with a specific tripId from Firestore.
 */
export const getExpensesForTrip = async (tripId: string): Promise<Expense[]> => {
  const expensesCollection = collection(db, 'expenses');
  const q = query(expensesCollection, where('tripId', '==', tripId));
  const querySnapshot = await getDocs(q);

  return querySnapshot.docs.map((doc) => {
    const data = doc.data();
    return {
      id: doc.id,
      tripId: data.tripId,
      groupId: data.groupId,
      amount: data.amount,
      currency: data.currency,
      category: data.category,
      date: data.date,
      description: data.description,
    } as Expense;
  });
};

/**
 * Saves document metadata to the 'documents' collection in Firestore.
 */
export const saveDocument = async (
  tripId: string,
  name: string,
  downloadUrl: string,
  eventId?: string
): Promise<Document> => {
  const documentsCollection = collection(db, 'documents');
  const data: any = {
    tripId,
    name,
    downloadUrl,
  };
  if (eventId) {
    data.eventId = eventId;
  }

  const docRef = await addDoc(documentsCollection, data);

  return {
    id: docRef.id,
    tripId,
    name,
    downloadUrl,
    ...(eventId ? { eventId } : {}),
  };
};

/**
 * Fetches all document metadata documents associated with a specific tripId from Firestore.
 */
export const getDocumentsForTrip = async (tripId: string): Promise<Document[]> => {
  const documentsCollection = collection(db, 'documents');
  const q = query(documentsCollection, where('tripId', '==', tripId));
  const querySnapshot = await getDocs(q);

  return querySnapshot.docs.map((doc) => {
    const data = doc.data();
    return {
      id: doc.id,
      tripId: data.tripId,
      eventId: data.eventId,
      name: data.name,
      downloadUrl: data.downloadUrl,
    } as Document;
  });
};
